name: Deploy Branch Sheanaok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Deploy ke VPS menggunakan SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 54.254.222.62   # Ganti dengan IP VPS Anda
          username: ubuntu  # Ganti dengan username SSH Anda
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Gunakan private key yang disimpan di GitHub Secret
          script: |
            cd /var/www/violation  # Ganti dengan path ke repositori di VPS
            git pull origin sheana
