name: Deploy to VPS

on:
  push:
    branches:
      - sheana  # Ganti dengan branch yang akan di-deploy

jobs:
  deploy:
    runs-on: debian 6.1.99-1

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Deploy ke VPS menggunakan SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 54.179.244.201  # Ganti dengan IP VPS Anda
          username: admin  # Ganti dengan username SSH Anda
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Gunakan private key yang disimpan di GitHub Secret
          script: |
            cd /var/www/dev_sman1ban_usr/data/www/dev.sman1bantarujeg.sch.id/violation  # Ganti dengan path ke repositori di VPS
            git pull origin sheana # Ganti dengan branch yang akan di-deploy
            composer install --no-dev
            composer update
            php artisan migrate
